# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Name_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5 import QtCore, QtGui, QtWidgets
from Chat import Ui_MainWindow_Chat

class Ui_MainWindow(object):
    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.window2=QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_Chat()
        self.ui.setupUi(self.window2)
    def Chat(self):
        
        
        self.window2.show()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(401, 420)
        MainWindow.setMinimumSize(QtCore.QSize(401, 420))
        MainWindow.setMaximumSize(QtCore.QSize(401, 420))
        MainWindow.setStyleSheet("\n"
"QWidget {\n"
"      background-color: #222222;\n"
"    background-color: rgb(77, 77, 77);\n"
" \n"
"}\n"
"\n"
"QLineEdit {\n"
"   background-color: aliceblue;\n"
"   color: #618b38;\n"
"   font-style: italic;\n"
"   font-weight: bold;\n"
"}\n"
"\n"
"QLabel {\n"
"   background-color: #222222;\n"
"   color: #618b38;\n"
"}\n"
"\n"
"QPushButton {\n"
"   background-color: #8b0000;\n"
"   color: #ffffff;\n"
"   border-radius: 5px;\n"
"   border-style: none;\n"
"   height: 25px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(100, 60, 211, 51))
        self.textEdit.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 150, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Pristina")
        font.setPointSize(34)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.Chat)
        self.pushButton.clicked.connect(MainWindow.close)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 401, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Enter"))
